apiVersion: v1
kind: Service
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 8080
    targetPort: 80
  selector:
    app: test-image
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  selector:
    matchLabels:
      app: test-image
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-image
        tier: frontend
    spec:
      containers:
      - image: muhammadadel8/newnginx:29
     # muhammadadel8/newnginx:29
        name: test-image
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
